# Generated by Django 3.1.2 on 2021-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='Date',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'observation"),
        ),
    ]
