# Generated by Django 3.1.2 on 2021-01-02 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_auto_20210102_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name="Date d'observation"),
        ),
    ]
