# Generated by Django 3.1.2 on 2021-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_auto_20210103_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel_labo',
            name='N_Martix',
            field=models.CharField(max_length=25, verbose_name='N° matricule'),
        ),
    ]
