# Generated by Django 2.2.7 on 2021-01-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_auto_20210103_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel_labo',
            old_name='N_Martix',
            new_name='N_Matrix',
        ),
    ]
